version: '3.9'

services:
  db:
    image: postgres:16
    container_name: pg-local
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./RealTimeChatApp
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=chatdb;Username=postgres;Password=secret"
    ports:
      - "5000:80"

volumes:
  pgdata: